import svg4everybody from 'svg4everybody';
import picturefill from 'picturefill';
import objectFitImages from 'object-fit-images';
import anchor from '../blocks/js-functions/anchor';
import { freezebuttons } from '../blocks/js-functions/freeze';
import scrollanimation from '../blocks/js-functions/scrollanimation';
import { selects, sliders, datepicker, inputmask, numberinput } from '../blocks/form-elements/form-elements';
import popups from '../blocks/popups/popups';
import scrollbar from '../blocks/scrollbar/scrollbar';
import slider from '../blocks/slider/slider';
import tooltips from '../blocks/tooltip/tooltip';
import tabs from '../blocks/tabs/tabs';
import maps from '../blocks/map/map';
import '../blocks/rating/rating';
import '../blocks/accordion/accordion';
import '../blocks/dropdown/dropdown';
import search from '../blocks/search/search';
import phoneShow from '../blocks/phone/phone';
import sidebar from '../blocks/js-functions/sidebar';
import highlightMenu from '../blocks/js-functions/highlightmenu';
import upShow from '../blocks/up-button/up-button';
import mixContent from '../blocks/grid-list/grid-list';
import { floatingLabels, validation, autosizeTextarea } from '../components/form/form';
import uploadFile from '../blocks/upload/upload';
import { linkHover, showLinkInfo } from '../components/sport-navigation/sport-navigation';
import locationPopup from '../components/location-popup/location-popup';

const $ = window.$;

$(() => {
  document.createElement('picture');
  svg4everybody();
  picturefill();
  objectFitImages();
  anchor();
  freezebuttons();
  selects();
  sliders();
  popups();
  scrollbar();
  slider();
  tooltips();
  tabs();
  datepicker();
  inputmask();
  numberinput();
  maps();
  scrollanimation();
  search();
  phoneShow();
  sidebar();
  highlightMenu();
  upShow();
  mixContent();
  floatingLabels();
  validation();
  uploadFile();
  linkHover();
  showLinkInfo();
  autosizeTextarea();
  locationPopup();
});
